- hosts: localhost
  become: true
  gather_facts: true
  ignore_errors: yes
  tasks:
    - include: tasks/terminal.yml
      tags: terminal
    - include: tasks/node.yml
      tags: node
    - include: tasks/git.yml
      tags: git
    - include: tasks/dev-tools.yml
      when: ansible_facts['distribution'] == "MacOSX"
      tags: dev-tools
    - include: tasks/personal-programs.yml
      when: ansible_facts['distribution'] == "MacOSX"
      tags: personal-programs
    - include: tasks/mobile.yml
      tags: mobile
    - include: tasks/rust.yml
      tags: rust
