- name: Install vscode
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present

- name: Install docker
  community.general.homebrew_cask:
    name: docker
    state: present

- name: Install postman
  community.general.homebrew_cask:
    name: postman
    state: present

- name: Install browsers
  community.general.homebrew_cask:
    name: ["brave-browser", "firefox", "google-chrome"]
    state: present
