- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "craciuncezar1996@gmail.com"

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Cezar Craciun"
