- name: '[macOS] Disable the "Are you sure you want to open this application?" dialog'
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
    state: present

- name: "[macOS] Trackpad - enable tap to click for this user and for the login screen"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: integer
    value: 1
    state: present
