- name: Install node
  community.general.homebrew:
    name: node
    state: present

- name: Install yarn
  community.general.homebrew:
    name: yarn
    state: present

- name: Install pnpm
  community.general.homebrew:
    name: pnpm
    state: present

- name: Install n
  npm:
    name: n
    global: yes
