- name: Install node
  community.general.homebrew:
    name: node
    state: present

- name: Install Yarn
  npm:
    name: yarn
    global: yes

- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
